"""The persistence the use cases depend on, stated as ports.

The application layer must not depend on how a record is stored — the same
reason `password_hasher.py` declares a `PasswordHasher` here while bcrypt lives
in `infrastructure/`. Before this, every use case imported a concrete
SQLAlchemy repository, so the dependency pointed outward and the layer could
not be exercised without the ORM.

These are `Protocol`s, so the classes in `app/repositories/` satisfy them by
shape alone: no base class, no registration, nothing to keep in sync beyond the
signatures. A fitness function forbids the application layer from importing
`app.repositories` directly, which is what keeps this file honest.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Protocol

from app.domain.models.board_meeting import BoardMeeting
from app.domain.models.deal import Deal
from app.domain.models.executive import Executive
from app.domain.models.monthly_indicator import MonthlyIndicator
from app.domain.models.monthly_indicator_token import MonthlyIndicatorToken
from app.domain.models.period import Period
from app.domain.models.startup import Startup
from app.domain.models.user import User
from app.domain.models.user_invite import UserInvite


class StartupRepository(Protocol):
    async def get_all(self) -> tuple[list[Startup], int]: ...
    async def get_by_id(self, startup_id: uuid.UUID) -> Startup | None: ...
    async def create(self, startup: Startup) -> Startup: ...
    async def update(self, startup: Startup) -> Startup: ...
    async def delete(self, startup: Startup) -> None: ...


class BoardMeetingRepository(Protocol):
    async def get_all_by_startup(
        self, startup_id: uuid.UUID
    ) -> tuple[list[BoardMeeting], int]: ...
    async def get_by_id(self, meeting_id: uuid.UUID) -> BoardMeeting | None: ...
    async def create(self, meeting: BoardMeeting) -> BoardMeeting: ...
    async def update(self, meeting: BoardMeeting) -> BoardMeeting: ...
    async def delete(self, meeting: BoardMeeting) -> None: ...
    async def get_startup_ids_with_recent_meetings(
        self, startup_ids: list[uuid.UUID], cutoff_days: int, reference_date: date
    ) -> set[uuid.UUID]: ...


class DealRepository(Protocol):
    async def get_all(self) -> tuple[list[Deal], int]: ...
    async def get_by_id(self, deal_id: uuid.UUID) -> Deal | None: ...
    async def create(self, deal: Deal) -> Deal: ...
    async def update(self, deal: Deal) -> Deal: ...
    async def delete(self, deal: Deal) -> None: ...


class ExecutiveRepository(Protocol):
    async def get_all_by_startup(
        self, startup_id: uuid.UUID
    ) -> tuple[list[Executive], int]: ...
    async def get_by_id(self, executive_id: uuid.UUID) -> Executive | None: ...
    async def create(self, executive: Executive) -> Executive: ...
    async def update(self, executive: Executive) -> Executive: ...
    async def delete(self, executive: Executive) -> None: ...


class MonthlyIndicatorRepository(Protocol):
    """Also owns the reporting tokens: one period, one link, one row.

    They share a repository because `get_or_create` and `get_or_create_token`
    resolve the same race on the same (startup, period) key.
    """

    async def get_all_by_startup(
        self, startup_id: uuid.UUID
    ) -> tuple[list[MonthlyIndicator], int]: ...
    async def get_by_id(self, indicator_id: uuid.UUID) -> MonthlyIndicator | None: ...
    async def get_by_startup_and_period(
        self, startup_id: uuid.UUID, month: int, year: int
    ) -> MonthlyIndicator | None: ...
    async def get_or_create(
        self, indicator: MonthlyIndicator
    ) -> tuple[MonthlyIndicator, bool]: ...
    async def update(self, indicator: MonthlyIndicator) -> MonthlyIndicator: ...
    async def delete(self, indicator: MonthlyIndicator) -> None: ...
    async def get_by_startups_and_period(
        self, startup_ids: list[uuid.UUID], month: int, year: int
    ) -> dict[uuid.UUID, MonthlyIndicator]: ...
    async def get_last_reported_period_by_startups(
        self, startup_ids: list[uuid.UUID], month: int, year: int
    ) -> dict[uuid.UUID, Period]: ...
    async def get_accumulated_revenue_by_startups(
        self, startup_ids: list[uuid.UUID], month: int, year: int
    ) -> dict[uuid.UUID, Decimal]: ...
    async def get_token_by_value(
        self, token: uuid.UUID
    ) -> MonthlyIndicatorToken | None: ...
    async def get_token_by_startup_and_period(
        self, startup_id: uuid.UUID, month: int, year: int
    ) -> MonthlyIndicatorToken | None: ...
    async def get_all_tokens_by_startup(
        self, startup_id: uuid.UUID
    ) -> tuple[list[MonthlyIndicatorToken], int]: ...
    async def get_or_create_token(
        self, token: MonthlyIndicatorToken
    ) -> tuple[MonthlyIndicatorToken, bool]: ...


class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_all(self) -> tuple[list[User], int]: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...


class UserInviteRepository(Protocol):
    async def create(self, invite: UserInvite) -> UserInvite: ...
    async def update(self, invite: UserInvite) -> UserInvite: ...
    async def get_by_token(self, token: uuid.UUID) -> UserInvite | None: ...
    async def get_active_by_email(
        self, email: str, now: datetime
    ) -> UserInvite | None: ...
    async def revoke(self, invite: UserInvite, now: datetime) -> UserInvite: ...
    async def mark_used(self, invite: UserInvite, now: datetime) -> UserInvite: ...
    async def get_all_active(self, now: datetime) -> tuple[list[UserInvite], int]: ...
